import type { Metadata } from "next";
import { Geist, Geist_Mono, Hedvig_Letters_Sans } from "next/font/google";
import "./globals.css";
import Nav from "./ui/nav";
import Header from "./ui/header";

import Footer from "./ui/footer";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kei Anana Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Nav /> */}
        <main className="min-h-screen">{children}</main>
        {/* <Footer /> */}
        <Analytics />
      </body>
    </html>
  );
}
