import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/app/ui/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kei Anana Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div className="w-screen h-48 flex flex-col flex-center justify-end items-center"> */}
        {/* <div className="w-full flex-none md:w-64"> */}
        <Nav />
        {/* </div> */}
        {/* </div> */}
        <div className="flex min-h-screen items-center justify-center font-sans">
          <main className="flex min-h-screen w-full max-w-3xl flex-col items-center py-8 justify-between sm:items-start">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
